module.exports =
	"ObojoboDraft.Chunks.Break": require "./src/scripts/node_modules/ObojoboDraft/Chunks/Break/editor"
	"ObojoboDraft.Chunks.Figure": require "./src/scripts/node_modules/ObojoboDraft/Chunks/Figure/editor"
	"ObojoboDraft.Chunks.Heading": require "./src/scripts/node_modules/ObojoboDraft/Chunks/Heading/editor"
	"ObojoboDraft.Chunks.HTML": require "./src/scripts/node_modules/ObojoboDraft/Chunks/HTML/editor"
	"ObojoboDraft.Chunks.IFrame": require "./src/scripts/node_modules/ObojoboDraft/Chunks/IFrame/editor"
	"ObojoboDraft.Chunks.List": require "./src/scripts/node_modules/ObojoboDraft/Chunks/List/editor"
	"ObojoboDraft.Chunks.Table": require "./src/scripts/node_modules/ObojoboDraft/Chunks/Table/editor"
	"ObojoboDraft.Chunks.YouTube": require "./src/scripts/node_modules/ObojoboDraft/Chunks/YouTube/editor"
	"ObojoboDraft.Chunks.MathEquation": require "./src/scripts/node_modules/ObojoboDraft/Chunks/MathEquation/editor"
	"ObojoboDraft.Chunks.Question": require "./src/scripts/node_modules/ObojoboDraft/Chunks/Question/editor"