const HEX_TYPE_ZERO_X = 'hexZeroX' //0xF9BA
const HEX_TYPE_OCTOTHORPE = 'hexOctothorpe' //#F9BA
const HEX_TYPE_DOLLAR_SIGN = 'hexDollarSign' //$F9BA
const HEX_TYPE_NO_PREFIX = 'hexNoPrefix' //F9BA
const HEX_TYPE_INFERRED = 'hexInferred' //1101

export {
	HEX_TYPE_ZERO_X,
	HEX_TYPE_OCTOTHORPE,
	HEX_TYPE_DOLLAR_SIGN,
	HEX_TYPE_NO_PREFIX,
	HEX_TYPE_INFERRED
}
