const INPUT_TYPE_SCIENTIFIC = 'scientific'
const INPUT_TYPE_DECIMAL = 'decimal'
const INPUT_TYPE_FRACTIONAL = 'fractional'
const INPUT_TYPE_HEXADECIMAL = 'hex'
const INPUT_TYPE_OCTAL = 'octal'
const INPUT_TYPE_BINARY = 'binary'
const INPUT_TYPE_INVALID = 'invalid'
const allTypes = [
	INPUT_TYPE_SCIENTIFIC,
	INPUT_TYPE_DECIMAL,
	INPUT_TYPE_FRACTIONAL,
	INPUT_TYPE_HEXADECIMAL,
	INPUT_TYPE_OCTAL,
	INPUT_TYPE_BINARY
]

module.exports = {
	INPUT_TYPE_SCIENTIFIC,
	INPUT_TYPE_DECIMAL,
	INPUT_TYPE_FRACTIONAL,
	INPUT_TYPE_HEXADECIMAL,
	INPUT_TYPE_OCTAL,
	INPUT_TYPE_BINARY,
	INPUT_TYPE_INVALID,
	allTypes
}
