const SCIENTIFIC_TYPE_X = 'x'
const SCIENTIFIC_TYPE_E = 'e'
const SCIENTIFIC_TYPE_EE = 'ee'
const SCIENTIFIC_TYPE_APOS = 'apos'
const SCIENTIFIC_TYPE_ASTERISK = 'asterisk'

module.exports = {
	SCIENTIFIC_TYPE_X,
	SCIENTIFIC_TYPE_E,
	SCIENTIFIC_TYPE_EE,
	SCIENTIFIC_TYPE_APOS,
	SCIENTIFIC_TYPE_ASTERISK
}
