const ROUND_TYPE_NONE = 'none'
const ROUND_TYPE_ROUND_SIG_FIGS = 'sig-figs'
const ROUND_TYPE_ROUND_DIGITS = 'digits'

module.exports = { ROUND_TYPE_NONE, ROUND_TYPE_ROUND_DIGITS, ROUND_TYPE_ROUND_SIG_FIGS }
