const ROUND_TYPE_NONE = 'none'
const ROUND_TYPE_ROUND_SIG_FIGS = 'sig-figs'
const ROUND_TYPE_ROUND_DECIMAL_DIGITS = 'decimals'

export { ROUND_TYPE_NONE, ROUND_TYPE_ROUND_DECIMAL_DIGITS, ROUND_TYPE_ROUND_SIG_FIGS }
