class Command
	constructor: (@type, @data = null) ->

Command.SET_CURSOR = 'setCursor'
Command.SELECT_TEXT = 'selectText'
Command.SELECT_CHUNK = 'selectChunk'
Command.SELECT_ALL = 'selectAll'
Command.INSERT_TEXT = 'insertText'
Command.REPLACE_TEXT = 'replaceText'
Command.STYLE_TEXT = 'styleText'
Command.UNSTYLE_TEXT = 'unstyleText'
Command.TOGGLE_STYLE_TEXT = 'toggleStyleText'
Command.SET_STYLE = 'setStyle'
Command.DELETE_TEXT = 'deleteText'
Command.SPLIT_TEXT = 'splitText'
Command.MERGE = 'merge'
Command.INSERT_HTML = 'insertHtml'
Command.INSERT_PAGE = 'insertPage'
Command.INSERT_PAGELET = 'insertPagelet'
Command.INSERT_CHUNK = 'insertChunk'
Command.CHANGE_CHUNK_TYPE = 'changeChunkType'
Command.CHANGE_LIST_TYPE = 'changeListType'
Command.INDENT = 'indent'
Command.INSERT_TAB = 'insertTab'
Command.CHANGE_SELECTION = 'changeSelection'
Command.MOVE = 'move'
Command.MOVE_END = 'moveEnd'
Command.UNDO = 'undo'
Command.REDO = 'redo'
Command.CLICK = 'click'
Command.MOUSE_DOWN = 'mouseDown'
Command.MOUSE_UP = 'mouseUp'
Command.FOCUS = 'focus'
Command.BLUR = 'blur'
Command.CONTEXT_MENU = 'contextMenu'
Command.CUT = 'cut'
Command.CUT_COMPLETE = 'cutComplete'
Command.INPUT = 'input'
Command.INPUT_COMPLETE = 'inputComplete'
Command.FOCUS_ENTER = 'focusEnter'

Command.POSITION_BEFORE = 'before'
Command.POSITION_AFTER = 'after'

Command.FOCUS_ENTER_TOP = 'top'
Command.FOCUS_ENTER_BOTTOM = 'bottom'

Command.DELETE_BACKWARD = 'backward'
Command.DELETE_FORWARD = 'forward'

module.exports = Command